#ifndef RAZONAMIENTO_H_
#define RAZONAMIENTO_H_
/* CREAR ESTRUCTURA CONSTRIBUYENTES
 * ALTA : INGRESAR NOMBRE, APELLIDO, Y CUIL, SE GENERA UN ID DESDE 1000 (MOSTRARLO)
 * MODIFICAR : INGRESO ID, PUEDO CAMBIAR NOMBRE, APELLIDO O CUIL
 * BAJA : INGRESO ID, VEO LA RECAUDACION DEL CONTRIBUYENTE, SI CONFIRMA BORRAR, BORRO CONTRIBUYENTE Y CONTRIBUCIONES
 *
 * CREAR ESTRUCTURA RECAUDACIONES
 * ALTA: INGRESAR ID DE CONTRIBUYENTE, MES, TIPO(HARDCODEAR) ARBA || IIBB || GANANCIAS, IMPORTE, SE GENERA ID DESDE 100 (MOSTRARLO)
 * REFINANCIAR: INGRESAR ID DE RECAUDACION, MOSTRAR INFO DE CONTRIBUYENTE, CAMBIAR DE ESTADO A REFINANCIADO (DE ESTADO DEUDOR)
 * SALDAR : INGRESAR ID DE RECAUDACION, MOSTRAR INFO DE CONTRIBUYENTE, CAMBIAR DE ESTADO A SALDADO
 *
 * IMPRIMIR CONTRIBUYENTES : (LECTURA) MOSTRAR TODOS LOS COTRIBUYENTES Y SUS CONTRIBUCIONES
 * IMPRIMIR RECAUDACION : (LECTURA) MOSTRAR TODAS LAS RECAUDACIONES DE ESTADO SALDADO, CON SUS DATOS, EL CUIL Y EL ID DE CONTRIBUYENTE
 *
 */


#endif /* RAZONAMIENTO_H_ */
